#!/usr/bin/env python
import sys
import urllib2
import os
import re

if len(sys.argv) < 4:
    print 'usage: %s <url> <name> <title>'%sys.argv[0]
    exit(1)

url = sys.argv[1]
file_name = sys.argv[2]
author = sys.argv[3]

print url
print file_name

#wget from url to local file
response = urllib2.urlopen(url)
html = response.read()

f = open(file_name + '.html','wb')
f.write(html)
f.close()

#run calibre's ebook-convert
if os.system('ebook-convert %s.html %s.azw3 --max-levels 0 --title %s --no-chapters-in-toc --insert-blank-line --authors %s'%(file_name,file_name,file_name,author)) != 0:
    print 'error running ebook-convert'
    exit(1)

os.remove('%s.html'%file_name)
