#!/usr/bin/env python
import sys
import urllib2
import os
import re

kindlegen='c:/utils/kindlegen/kindlegen'
url = sys.argv[1]
file_name = sys.argv[2]

print url
print file_name

#wget from url to local file
response = urllib2.urlopen(url)
html = response.read()

html = re.sub('<(/)?(A|a)([^A-Za-z>][^>]*>|>)', '', html)
f = open(file_name + '.html','wb')
f.write(html)
f.close()

#run calibre's ebook-convert
if os.system('ebook-convert %s.html %s.epub --max-levels 0 --title %s --no-chapters-in-toc --insert-blank-line'%(file_name,file_name,file_name)) != 0:
    print 'error running ebook-convert'
    exit(1)

#run kindle-gen on result
os.system('%s %s.epub -o %s.mobi'%(kindlegen,file_name,file_name))


#cleanup temp files
#os.remove('%s.epub'%file_name)
#os.remove('%s.html'%file_name)
